15:30 Create a new git repo
15:31 Need to fix some bugs
15:32 Need to complete the python projets

IDE stands for Integrated Development Environment.It's a tool where you can write the code and at the same time you can compile run and debug thr program.
In code editors you can edit all types of file instead of specializing in a particular type or language.sure you can have plugins, specific for a type of file or language, that compiles/runs/debugs but since is it done by plugins, I guess the "integrated" part is of of the table, so doesn't make much sense to cal it IDE